### ISSUE TITLE
MODX 3 compatibility

### ISSUE THREAD

**Issue by lottaar** [modxcms/fred-rte-tinymce#28]
Any plans to make it compatible with MODX 3, or is there another RTE that can be used with Fred in MODX 3?

**Comment by neoneddy** [comment]
Plus 1

**Comment by theboxer** [comment]
Fixed, needs Fred 2.0.2

**Comment by neoneddy** [comment]
Anyone else having FRED fail to load  after this update and Tiny MCE for Fred installed?

**Comment by neoneddy** [comment]
@theboxer  I still get a eternal preparing content spinner 
![image](https://user-images.githubusercontent.com/819083/198340901-6219f9bc-2054-44a4-878a-121ee34fbc5d.png)
 Updated Fed and Tiny MCE for Fred and removed all other Fred editors.
